### ISSUE TITLE
7 - changer toutes les références à "Academy VR Games"

### ISSUE THREAD

**Issue by yanngv29** [yanngv29/ensim-git-tp3#7]
Changer dans la page "Academy VR Games" en "Les JV de l'ENSIM"

**Comment by RezkB** [comment]
Je m'en occupe. -Rezk BERCHID

**Comment by yanngv29** [comment]
Bonjour, 

Il me semble que tu n'as pas modifié Tous les Academy VR Games de la page ... normalement il y en a 3.  Merci de vérifier.
